### ISSUE TITLE
New workflows for hi-ml fail with an odd import problem

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/hi-ml#421]
Example run: https://github.com/microsoft/hi-ml/runs/6782781947?check_suite_focus=true

One of the associated runs in AML fails like this:

```python-traceback
Traceback (most recent call last):
  File "test_script.py", line 16, in <module>
    from health_azure import DatasetConfig, submit_to_azure_if_needed
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/health_azure/__init__.py", line 6, in <module>
    from health_azure.datasets import DatasetConfig
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/health_azure/datasets.py", line 10, in <module>
    from azureml.core import Dataset, Datastore, Workspace
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/azureml/core/__init__.py", line 13, in <module>
    from .workspace import Workspace
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/azureml/core/workspace.py", line 22, in <module>
    from azureml._project import _commands
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/azureml/_project/_commands.py", line 8, in <module>
    from azureml._restclient.clientbase import ClientBase
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/azureml/_restclient/__init__.py", line 7, in <module>
    from .rest_client import RestClient
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/azureml/_restclient/rest_client.py", line 12, in <module>
    from msrest.service_client import ServiceClient
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/msrest/__init__.py", line 28, in <module>
    from .configuration import Configuration
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/msrest/configuration.py", line 38, in <module>
    from .universal_http.requests import (
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/msrest/universal_http/__init__.py", line 53, in <module>
    from ..exceptions import ClientRequestError, raise_with_traceback
  File "/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/msrest/exceptions.py", line 31, in <module>
    from azure.core.exceptions import SerializationError, DeserializationError
ImportError: cannot import name 'SerializationError' from 'azure.core.exceptions' (/azureml-envs/azureml_ef7e96329c290639d6da332e7aa85ec3/lib/python3.7/site-packages/azure/core/exceptions.py)
```
Failing AML job: test_script_1654675836_b7173de9

**Comment by mebristo** [comment]
I did some digging - this occurs because SerializationError and DeserializationError are [removed from msrest as of version 0.7.0](https://github.com/Azure/msrest-for-python/pull/247/files#diff-7d79f3857510eee95c1d013f1426e0a16e330f668ede08dcecc702b07d18864f) and instead [added into azure-core from version 1.24.0](https://github.com/Azure/azure-sdk-for-python/pull/24312/files). The latest `azureml-core` (1.42.0) has an upper limit on `azure-core` of 1.22.1. So the proper fix here is that `azureml-core` increases this upper limit to allow 1.24.0, and then we update to the latest `azureml-sdk`. The temporary workaround is that we pin to `msrest==0.6.21` for now
