### ISSUE TITLE
Smoke tests still not working using v2 SDK

### ISSUE THREAD

**Issue by peterhessey** [microsoft/hi-ml#733]
Even after the `wait_for_completion` fix, the `cpath` smoke tests still fail when not restricted using the `--strictly_aml_v1` flag. It appears the v2 SDK is checking for README files that it can't find:

```console
2023-01-16T10:10:17.5913440Z { cd ../ ; python ***/src/health_ml/runner.py --mount_in_azureml --conda_env=***-cpath/environment.yml --datastore=himldatasets --model=health_cpath.TilesPandaImageNetMIL --tune_encoder --batch_size=2 --pl_limit_train_batches=2 --pl_limit_val_batches=2 --pl_limit_test_batches=2 --max_epochs=2 \
2023-01-16T10:10:17.5914847Z --crossval_count=0 --num_top_slides=2 --num_top_tiles=2 --max_bag_size=3 --max_bag_size_inf=3  --cluster=dedicated-nc24s-v2 --wait_for_completion --max_run_duration=1h --tag smoke_test_tilespandaimagenetmil_aml;}
2023-01-16T10:10:21.2687399Z project root: /home/runner/work/***/***
2023-01-16T10:10:21.2688166Z Setting up logging to stdout.
2023-01-16T10:10:21.2688760Z Setting logging level to 20
2023-01-16T10:10:21.2689772Z 2023-01-16T10:10:21Z INFO     rpdb is handling traps. To debug: identify the main runner.py process, then as root: kill -TRAP <process_id>; nc 127.0.0.1 4444
2023-01-16T10:10:21.2704358Z 2023-01-16T10:10:21Z INFO     Trying to locate model health_cpath.TilesPandaImageNetMIL
2023-01-16T10:10:22.8618526Z 2023-01-16T10:10:22Z INFO     Failed to extract font properties from /usr/share/fonts/truetype/noto/NotoColorEmoji.ttf: In FT2Font: Can not load face.  Unknown file format.
2023-01-16T10:10:22.8689822Z 2023-01-16T10:10:22Z INFO     generated new fontManager
2023-01-16T10:10:27.7619510Z 2023-01-16T10:10:27Z INFO     Found class <class 'health_cpath.configs.classification.DeepSMILEPanda.TilesPandaImageNetMIL'> in file /home/runner/work/***/***/***-cpath/src/health_cpath/configs/classification/DeepSMILEPanda.py
2023-01-16T10:10:27.7824631Z 2023-01-16T10:10:27Z INFO     Trying to locate the workspace config file 'config.json' in the current folder and its parent folders
2023-01-16T10:10:27.7825499Z 2023-01-16T10:10:27Z INFO     Using the workspace config file /home/runner/work/***/***/config.json
2023-01-16T10:10:27.7826236Z 2023-01-16T10:10:27Z INFO     Found all necessary environment variables for Service Principal authentication.
2023-01-16T10:10:27.7868578Z 2023-01-16T10:10:27Z INFO     Found the config file in: /home/runner/work/***/***/config.json
2023-01-16T10:10:29.7050423Z 2023-01-16T10:10:29Z INFO     Logged into AzureML workspace *** as specified in config file /home/runner/work/***/***/config.json
2023-01-16T10:10:30.3501764Z 2023-01-16T10:10:30Z INFO     ClientSecretCredential.get_token succeeded
2023-01-16T10:10:30.3502919Z 2023-01-16T10:10:30Z INFO     Trying to locate the workspace config file 'config.json' in the current folder and its parent folders
2023-01-16T10:10:30.3503962Z 2023-01-16T10:10:30Z INFO     Using the workspace config file /home/runner/work/***/***/config.json
2023-01-16T10:10:30.3505543Z 2023-01-16T10:10:30Z INFO     Found all necessary environment variables for Service Principal authentication.
2023-01-16T10:10:30.3507486Z 2023-01-16T10:10:30Z INFO     Found the config file in: /home/runner/work/***/***/config.json
2023-01-16T10:10:32.4067506Z 2023-01-16T10:10:32Z INFO     Logged into AzureML workspace *** as specified in config file /home/runner/work/***/***/config.json
2023-01-16T10:10:32.4112167Z 2023-01-16T10:10:32Z INFO     Logged into AzureML workspace ***
2023-01-16T10:10:32.4112874Z 2023-01-16T10:10:32Z INFO     Using this Conda environment definition: ***-cpath/environment.yml
2023-01-16T10:10:33.4661564Z Loaded AzureML workspace ***
2023-01-16T10:10:33.4662194Z 2023-01-16T10:10:33Z INFO     Didn't find existing environment. Registering a new one.
2023-01-16T10:10:46.8478172Z 2023-01-16T10:10:46Z INFO     Logged into AzureML workspace ***
2023-01-16T10:10:48.3214731Z Traceback (most recent call last):
2023-01-16T10:10:48.3215692Z   File "/usr/share/miniconda/envs/HimlHisto/lib/python3.9/site-packages/azure/ai/ml/operations/_operation_orchestrator.py", line 255, in _get_code_asset_arm_id
2023-01-16T10:10:48.3218299Z     code_asset = self._code_assets.create_or_update(code_asset)
2023-01-16T10:10:48.3219549Z   File "/usr/share/miniconda/envs/HimlHisto/lib/python3.9/site-packages/azure/ai/ml/operations/_code_operations.py", line 141, in create_or_update
2023-01-16T10:10:48.3220418Z     raise ex
2023-01-16T10:10:48.3221769Z   File "/usr/share/miniconda/envs/HimlHisto/lib/python3.9/site-packages/azure/ai/ml/operations/_code_operations.py", line 94, in create_or_update
2023-01-16T10:10:48.3222773Z     code, _ = _check_and_upload_path(
2023-01-16T10:10:48.3224074Z   File "/usr/share/miniconda/envs/HimlHisto/lib/python3.9/site-packages/azure/ai/ml/_artifacts/_artifact_utilities.py", line 399, in _check_and_upload_path
2023-01-16T10:10:48.3225386Z     uploaded_artifact = _upload_to_datastore(
2023-01-16T10:10:48.3226636Z   File "/usr/share/miniconda/envs/HimlHisto/lib/python3.9/site-packages/azure/ai/ml/_artifacts/_artifact_utilities.py", line 297, in _upload_to_datastore
2023-01-16T10:10:48.3227753Z     artifact = upload_artifact(
2023-01-16T10:10:48.3228996Z   File "/usr/share/miniconda/envs/HimlHisto/lib/python3.9/site-packages/azure/ai/ml/_artifacts/_artifact_utilities.py", line 178, in upload_artifact
2023-01-16T10:10:48.3229963Z     artifact_info = storage_client.upload(
2023-01-16T10:10:48.3231153Z   File "/usr/share/miniconda/envs/HimlHisto/lib/python3.9/site-packages/azure/ai/ml/_artifacts/_blob_storage_helper.py", line 91, in upload
2023-01-16T10:10:48.3232125Z     file_size, _ = get_directory_size(source)
2023-01-16T10:10:48.3233312Z   File "/usr/share/miniconda/envs/HimlHisto/lib/python3.9/site-packages/azure/ai/ml/_utils/_asset_utils.py", line 410, in get_directory_size
2023-01-16T10:10:48.3234830Z     path_size = os.path.getsize(
2023-01-16T10:10:48.3235837Z   File "/usr/share/miniconda/envs/HimlHisto/lib/python3.9/genericpath.py", line 50, in getsize
2023-01-16T10:10:48.3249955Z     return os.stat(filename).st_size
2023-01-16T10:10:48.3251070Z FileNotFoundError: [Errno 2] No such file or directory: '../../***-multimodal/README.md'
```

**Comment by mebristo** [comment]
This is because the file 'docs/source/multimodal.md' is symlinked, and AML (v2) evaluates the symlink and then tries to find that relative path
