### ISSUE TITLE
Errors getting display name and using `after_submission_hook`

### ISSUE THREAD

**Issue by fepegar** [microsoft/hi-ml#773]
I'm having some issues submitting with `hi-ml-azure==0.2.14`.

---

First, this:

```python-traceback
Traceback (most recent call last):
  File "common/azure/submit_to_aml.py", line 74, in <module>
    wait_for_completion=args.wait_for_completion,
  File "/home/fernando/git/JointChestXray/common/azure/aml.py", line 243, in submit_aml_job
    tags=set_tags(tags, script_config))
  File "/home/fernando/miniconda3/envs/JointChestXray/lib/python3.7/site-packages/health_azure/himl.py", line 992, in submit_to_azure_if_needed
    pytorch_processes_per_node=pytorch_processes_per_node_v2,
  File "/home/fernando/miniconda3/envs/JointChestXray/lib/python3.7/site-packages/health_azure/himl.py", line 538, in submit_run_v2
    display_name = get_display_name_v2(tags)
  File "/home/fernando/miniconda3/envs/JointChestXray/lib/python3.7/site-packages/health_azure/himl.py", line 430, in get_display_name_v2
    display_name = tag.replace(" ", "-")
AttributeError: 'NoneType' object has no attribute 'replace'
```

I suspect the `tags` dict does have a `tag` key with value `None`, causing this error.

--- 

So I set a tag to get around this, but I have a new error now:

```python-traceback
Traceback (most recent call last):
  File "common/azure/submit_to_aml.py", line 74, in <module>
    wait_for_completion=args.wait_for_completion,
  File "/home/fernando/git/JointChestXray/common/azure/aml.py", line 243, in submit_aml_job
    tags=set_tags(tags, script_config))
  File "/home/fernando/miniconda3/envs/JointChestXray/lib/python3.7/site-packages/health_azure/himl.py", line 995, in submit_to_azure_if_needed
    after_submission(job, ml_client)  # type: ignore
TypeError: after_submission_hook() takes 1 positional argument but 2 were given
```

Do we need to reimplement our `after_submission_hook`?

**Comment by ant0nsc** [comment]
@fepegar , regarding the second issue - yes, the `after_submission_hook` takes two arguments in v2. For flexibility, I'd suggest a signature like `after_submission_hook(azure_run: Run, *args: Any)` to go flexibly between v1 and v2 SDK.

**Comment by ant0nsc** [comment]
For the first issue regarding tags, can you add the arguments that you supply to `submit_to_azure_if_needed` ?

**Comment by fepegar** [comment]
Thanks. This is the error I get when adding `*args: Any` to the signature:

```python-traceback
Traceback (most recent call last):
  File "common/azure/submit_to_aml.py", line 74, in <module>
    wait_for_completion=args.wait_for_completion,
  File "/home/fernando/git/JointChestXray/common/azure/aml.py", line 243, in submit_aml_job
    tags=set_tags(tags, script_config))
  File "/home/fernando/miniconda3/envs/JointChestXray/lib/python3.7/site-packages/health_azure/himl.py", line 995, in submit_to_azure_if_needed
    after_submission(job, ml_client)  # type: ignore
  File "/home/fernando/git/JointChestXray/common/azure/aml.py", line 194, in after_submission_hook
    aml_url = run.get_portal_url()
TypeError: '_AttrDict' object is not callable
```

**Comment by fepegar** [comment]
> For the first issue regarding tags, can you add the arguments that you supply to submit_to_azure_if_needed ?

The `tags` dict includes `tag: None`. Would you like all of them?

**Comment by ant0nsc** [comment]
That's because, when using SDK v2, there is no more "Run" object. The signature has been changed to
```
after_submission: Optional[Union[Callable[[Run], None], Callable[[Job, MLClient], None]]] = None,
```
When submitting via V1, you get a `Run` object. for V2, you get a tuple `Job, MLClient`.

**Comment by mebristo** [comment]
We could update `get_display_name_v2` to return `<job>.display_name` if `tags.get("tag")` is None (i.e. --tag hasn't been provided on commandline)?

**Comment by ant0nsc** [comment]
@mebristo , we should rather re-think how we handle display names. Now that display names are first class citizens in AML SDK, we should set them directly upon job submission, rather than in hooks and passed around in a tags dictionary.

**Comment by ant0nsc** [comment]
Tackling the display name problem in #774

**Comment by ant0nsc** [comment]
@fepegar are we good to close this one?

**Comment by fepegar** [comment]
I think so. Thanks, @ant0nsc.
